### ISSUE TITLE
[Bug]  Error: expected timestamp at row 1, but received: "��1 

### ISSUE THREAD

**Issue by speedbmp** [DrKain/subclean#32] opened 2023-08-12 17:27 UTC
[Clean] [561/6192] Cleaning "Animal House.bluray.srt"
[Error] Unable to parse "Z:\VS-Movies\Animal House (1978)\Animal House.bluray.srt"
[Error] Please create an issue on GitHub with a copy of this file.

[Error] Error: expected timestamp at row 1, but received: "��1   "

[Animal House.bluray - Copy.txt](https://github.com/DrKain/subclean/files/12327932/Animal.House.bluray.-.Copy.txt)

**Comment by speedbmp** [comment] 2023-08-12 17:27
rename the file and remove .txt and change to .srt

**Comment by DrKain** [comment] 2023-08-12 18:09
Thanks for reporting. This is a duplicate of #8 (same issue, different character encoding).  
You can fix the current subtitle with the Bazarr setting mentioned in the linked issue or using Notepad++ (Encoding -> Convert to UTF-8)  

I do plan on adding a parameter to convert these subs when found, but I don't have the time for it right now.

**Closed as completed by DrKain** 2023-08-12 18:09 UTC
Labels: bug, priority: medium

**Comment by speedbmp** [comment] 2023-08-12 18:17
Sounds good thanks
